### ISSUE TITLE
Basic heightmap option

### ISSUE THREAD

**Issue by IdrisQe** [Hunternif/AntiqueAtlas#247]
I adore AA, but one thing that's been a consistent hinderance is that it only does biomes.
With the "new" structure support, more detailed maps have been made possible, accurately mapping villages, Nether Fortresses, etc., but for normal terrain it's still stuck with mostly just biomes, which when it comes to navigation, is very limited.

While I understand this would make things a lot more difficult, I feel having an option to turn on a rudimentary heightmap would be great. A configurable height detector of sorts, which would show a "step up" in the terrain much like the walls of the Nether show up as, when the average height of an area is significantly higher than the average height of the surrounding areas, by say, 8 blocks.

**Comment by Hunternif** [comment]
That would certainly be a nice feature. It might be a ton of work to do correctly: basically every texture would need an "elevated" alternative. But I'll see if maybe using the exising hills textures will work.

**Comment by IdrisQe** [comment]
Oh, I was moreso thinking of using an already existing "this area is higher" texture and then layering the biome textures above. I'm not certain that's possible, as I don't know if the current textures utilize transparency, but if they do, I feel like it should be doable. 
Something like this (don't mind the quick mockup with awful tiling and lack of smoothness):
![image](https://user-images.githubusercontent.com/40530630/70427203-2716ac00-1a29-11ea-9a1d-9089ef18da12.png)
Where the middle area shows with the "step up" texture is on average 4-8 blocks higher than the surrounding area.

**Comment by tyra314** [comment]
As 1.18 did a complete overhaul of the worldgen and how biomes work, this is now partially a thing. Instead of hard heightmap lines though, AA will choose matching textures for configured biomes with hills or mountains depending on the height value. So it's more subtle than in the screenshot, but it's there.

For example, this is all plains biome, but different textures depending on the height value:

![image](https://user-images.githubusercontent.com/16997177/211202807-e9f5191e-f567-425f-b3eb-1b10eb88a21d.png)
