### ISSUE TITLE
Death Markers and Corpse Complex Issue

### ISSUE THREAD

**Issue by Kortako** [Hunternif/AntiqueAtlas#277]
[Corpse Complex](https://www.curseforge.com/minecraft/mc-mods/corpse-complex) allows a modpack maker to change a variety of options for player death, and one of the options set in the current modpack I'm playing ([RotN: BPG](https://www.curseforge.com/minecraft/modpacks/rotn-bpg-edition)) is that the atlas book is in a whitelist of items not dropped on death.  This seems to prevent the atlas from creating death markers when you die.  In my testing, if you remove the atlas from the whitelist config and allow it to drop when you die, the death marker functionality is restored.

**Comment by tyra314** [comment]
So what you're saying is that you don't want to get a death marker into the atlas?

Well, there's a config option for that: `autoDeathMarker`

**Comment by Kortako** [comment]
Sorry, I should have been more clear. What I mean is, I **do** want the death marker to appear, but because the Atlas does not drop on death, the marker doesn't get created. When I die, everything else does drop, so I would want the marker ideally.

**Comment by tyra314** [comment]
I looked into this issue, but unfortunately, I can do nothing, which isn't a dirty hack. I'm not even sure if there is a solution to this problem without breaking something else. On player death, Corpse complex is very eagerly* removing the player inventory according to their rules. So when AntiqueAtlas finally has a chance for writing its markers, all atlas items are already gone. Therefore, AntiqueAtlas can't know in which atlases to store the death marker. You might report this issue to Corpse Complex and hope for a solution from them, but I doubt they'll arrive at a different sentiment.

So probably you have to pick your poison: i.e., death markers, or keep atlas on death.

*They probably are that eager, because otherwise, something else² will break.
²Turns out, they needed to be fast to fix some issue in conjunction with the curios mod.
